# Generated by Django 3.1.1 on 2020-11-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify',
            old_name='anwsers',
            new_name='answers',
        ),
    ]
